### ISSUE TITLE
Which stories still need to be hooked up to APIs?

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#57]
We want to the city to be able to push new data to the Homelessness Collection, so the existing stories front end should be able to support new data coming in.

We need to do some assessment of the existing stories and APIs: 

Which APIs are not hooked up? 
Which APIs are not ready?
Which stories will this affect? How do we prep them for the future?

**Comment by clemf** [comment]
Definition - API connected
Population - API connected
Migration - Hardcoded
Youth - Hardcoded (text)
Women - Hardcoded
Services211 - API connected

I believe Migration and Women can be connected to the API. Setting up the API so that future data can be pushed in is an interesting challenge. To be honest I find some of the ways the endpoints have been set up to be a little nonsensical. It may be worth some meetings to talk about improving how the data is provided.

**Comment by outerpress** [comment]
Thanks @clemf! I created two new issues for Migration/Women cards, and will write up our plan for improving the APIs.
