### ISSUE TITLE
Hook up Migration Card to API

### ISSUE THREAD

**Issue by outerpress** [hackoregon/teamHomelessness-frontend#58]
http://homelessness.civicpdx.org/migration needs to be hooked up to the API

**Comment by clemf** [comment]
For the tree map, that data is simply not available in the API.

For the "12%" number, I don't think that is in the API either. The [/migration](http://service.civicpdx.org/homeless/#!/migration/migration_list) endpoint lists percentages of various areas that people moved from, but they do not add up to anything near 12%.

**Comment by outerpress** [comment]
The 12% comes from page 36 of PIT draft report 2015. Here's a screencap:

<img width="512" alt="capture" src="https://user-images.githubusercontent.com/2536801/27523964-f20c9232-59e5-11e7-9645-a43422508699.PNG">

**Comment by outerpress** [comment]
The percentages in the tree map come from page 37 of PIT draft report 2015:

<img width="349" alt="capture" src="https://user-images.githubusercontent.com/2536801/27524058-8e0288ea-59e6-11e7-8d58-1a60037de7e1.PNG">

These look correct in http://service.civicpdx.org/homeless/#!/migration/migration_list.

**Comment by clemf** [comment]
Ok I see, I was just thrown off by the decimal format of the percentages.

Should we make an endpoint for the "homeless when they came here" numbers? It would be cool to get both years in the app. That's also a pretty important number in context of the homelessness issue.

**Comment by Zak-Kent** [comment]
We could calculate the numbers and just round up/down accordingly and add those as a field to the existing table. It looks like those numbers refer to the 224 people in the 2015 count that were homeless when they came.

**Comment by clemf** [comment]
@outerpress What do you think of this? Obviously the margins need to be tweaked, but I'm trying to standardize the "half donut" chart so that the same one is being used across the site. It's not necessary to have the legend and "year link" show up, but if we fixed the styling is that something you'd want?

<img width="651" alt="screen shot 2017-06-27 at 8 24 57 pm" src="https://user-images.githubusercontent.com/10442838/27619412-ec32c29a-5b76-11e7-8aa1-643e0ada4812.png">

**Comment by clemf** [comment]
Done in #65
